# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal_detective.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.horizontalLayout.addLayout(self.plotLayout)
        self.controlLayout = QtWidgets.QVBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startPosition = QtWidgets.QSpinBox(self.centralwidget)
        self.startPosition.setObjectName("startPosition")
        self.horizontalLayout_2.addWidget(self.startPosition)
        self.endPosition = QtWidgets.QSpinBox(self.centralwidget)
        self.endPosition.setMaximum(5000000)
        self.endPosition.setProperty("value", 1250)
        self.endPosition.setObjectName("endPosition")
        self.horizontalLayout_2.addWidget(self.endPosition)
        self.controlLayout.addLayout(self.horizontalLayout_2)
        self.frequencyLayout = QtWidgets.QHBoxLayout()
        self.frequencyLayout.setObjectName("frequencyLayout")
        self.frequency = QtWidgets.QSpinBox(self.centralwidget)
        self.frequency.setMaximum(3000)
        self.frequency.setProperty("value", 250)
        self.frequency.setObjectName("frequency")
        self.frequencyLayout.addWidget(self.frequency)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.frequencyLayout.addWidget(self.label)
        self.controlLayout.addLayout(self.frequencyLayout)
        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setObjectName("importButton")
        self.controlLayout.addWidget(self.importButton)
        self.filterCommandText = QtWidgets.QTextEdit(self.centralwidget)
        self.filterCommandText.setObjectName("filterCommandText")
        self.controlLayout.addWidget(self.filterCommandText)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.controlLayout.addWidget(self.runButton)
        self.controlLayout.setStretch(0, 1)
        self.controlLayout.setStretch(1, 1)
        self.controlLayout.setStretch(2, 1)
        self.controlLayout.setStretch(3, 5)
        self.controlLayout.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.controlLayout)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIGNAL-DETECTIVE"))
        self.label.setText(_translate("MainWindow", "hz"))
        self.importButton.setText(_translate("MainWindow", "import"))
        self.runButton.setText(_translate("MainWindow", "run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
